spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zzc_blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
#redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 1
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 500
      min-idle: 0
    timeout: 0
server:
  port: 8012
